# Generated by Django 2.2 on 2019-04-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('url', models.URLField()),
                ('description', models.TextField(blank=True, default='')),
                ('date', models.DateField(auto_now_add=True)),
                ('date_mod', models.DateField(auto_now=True)),
                ('license', models.CharField(choices=[('RIG', 'COPYRIGHT'), ('C_C', 'CREATE_COMMONS'), ('LEFT', 'COPYLEFT')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_completo', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=150)),
                ('foto', models.CharField(max_length=150000)),
            ],
        ),
    ]
