# Generated by Django 2.2 on 2019-04-25 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='license',
            field=models.CharField(choices=[('C_C', 'CREATE_COMMONS'), ('LEFT', 'COPYLEFT'), ('RIG', 'COPYRIGHT')], max_length=3),
        ),
    ]
